import 'package:flutter/material.dart';
import 'player_settings_sheet.dart';

/// Helper function to show player settings bottom sheet
/// Returns a Future that completes when the sheet is dismissed
Future<void> showPlayerSettingsSheet({
  required BuildContext context,
  required bool autoPlay,
  required bool loop,
  required bool forceHD,
  required bool enableCaption,
  required bool isMuted,
  required Color settingsBackgroundColor,
  required Color settingItemBackgroundColor,
  required Color iconColor,
  required Color textColor,
  Color? switchInactiveThumbColor,
  Color? switchInactiveTrackColor,
  TextStyle? titleTextStyle,
  TextStyle? itemTextStyle,
  required String playerSettingsText,
  required String autoPlayText,
  required String loopVideoText,
  required String forceHdQualityText,
  required String enableCaptionsText,
  required String muteAudioText,
  required bool showAutoPlaySetting,
  required bool showLoopSetting,
  required bool showForceHDSetting,
  required bool showCaptionsSetting,
  required bool showMuteSetting,
  required Future<void> Function(bool) onAutoPlayChanged,
  required Future<void> Function(bool) onLoopChanged,
  required Future<void> Function(bool) onForceHDChanged,
  required Future<void> Function(bool) onEnableCaptionChanged,
  required void Function(bool) onMutedChanged,
}) {
  return showModalBottomSheet(
    context: context,
    backgroundColor: settingsBackgroundColor,
    shape: const RoundedRectangleBorder(
      borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
    ),
    builder: (context) => PlayerSettingsSheet(
      autoPlay: autoPlay,
      loop: loop,
      forceHD: forceHD,
      enableCaption: enableCaption,
      isMuted: isMuted,
      iconColor: iconColor,
      textColor: textColor,
      settingItemBackgroundColor: settingItemBackgroundColor,
      switchInactiveThumbColor: switchInactiveThumbColor,
      switchInactiveTrackColor: switchInactiveTrackColor,
      titleTextStyle: titleTextStyle,
      itemTextStyle: itemTextStyle,
      playerSettingsText: playerSettingsText,
      autoPlayText: autoPlayText,
      loopVideoText: loopVideoText,
      forceHdQualityText: forceHdQualityText,
      enableCaptionsText: enableCaptionsText,
      muteAudioText: muteAudioText,
      showAutoPlaySetting: showAutoPlaySetting,
      showLoopSetting: showLoopSetting,
      showForceHDSetting: showForceHDSetting,
      showCaptionsSetting: showCaptionsSetting,
      showMuteSetting: showMuteSetting,
      onAutoPlayChanged: onAutoPlayChanged,
      onLoopChanged: onLoopChanged,
      onForceHDChanged: onForceHDChanged,
      onEnableCaptionChanged: onEnableCaptionChanged,
      onMutedChanged: onMutedChanged,
    ),
  );
}